
support:
    database:
        type: "tinydb"
        path: "/tmp/data_manager_db.json"

    get_url:
        expiration: 518400

data_manager:
    table_name: "data"

    autosplit:
        seed: 42
        train_percent: 50.0

    export:
        table_name: "exported"
        path: "s3://peoples-speech/datasets/prestamo"

    upload:
        path: "s3://peoples-speech/datasets/prestamo/uploads"

transcription:
    task_table_name: "transcription_tasks"

alignment:
    vad:
        frame_duration_ms: 30
        padding_duration_ms: 120
        voiced_frame_ratio: 0.9

align:
    minimum_return_confidence: 0.0
    minimum_update_confidence: 40.0
    minimum_speech_confidence: 50.0
    minimum_alignment_confidence: 50.0

segment:
    type : "forced-alignment"

deploy:
    device_table_name: "devices"
    metrics_table_name: "metrics"
    predict_endpoint: "http://deploy:5002/peoples_speech/predict"

    model:
        path: "s3://peoples-speech/models/prestamo/04dae9c2bf4f705fb8068fdb33a4d8e0/best"
        type: "google"
        language: "en"
        google_cloud_storage_path: "gs://peoples-speech/google-speech-to-text-staging"

    test:
        audio_path: "s3://peoples-speech/examples/prestamo/audio/gtts-prestamo.flac"
        audio_label: "none"

model_iteration:
    training_path: "s3://peoples-speech/models/prestamo"
    job_table_name: "training_jobs"

    trainer:
        type: "remote"
        endpoint: "http://trainer:5555/remote_trainer/train"
        model:
            type: "keyword"
            label: "prestamo"
            repeat: 4
            batch_size: 2
            epochs: 10
            patience: 3
            shuffle_buffer_size: 16

            save_path: "s3://peoples-speech/models/prestamo/efc19a0d2ebba02e26281a8235ece1c6"
            local_save_path: "/app/models"
            results_path: "s3://peoples-speech/models/prestamo/efc19a0d2ebba02e26281a8235ece1c6/results.json"

        dataset:
            path: "s3://peoples-speech/datasets/prestamo/955c16269fbd3fe2553e203e56a0b8c6.jsonlines"

account:
    whitelist: ["gregory.diamos@gmail.com"]

credentials:
    path: "/home/ubuntu/.aws/credentials"

target: "x86"

verbose: True
verbose_info: True
aws_region: us-east-2

